FROM postgres:9.6

COPY ./db/migrations/1_create_users.up.sql /docker-entrypoint-initdb.d/

RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
ENV LANG ja_JP.utf8
ENV POSTGRES_USER unko_user
ENV POSTGRES_DB unko